


function hashmap(props) {

const collection = new Map();
//Comienzo del hashmap
collection.set('tench, Tinca tinca',"No tengo información de como reciclarlo");
collection.set('goldfish, Carassius auratus',"No tengo información de como reciclarlo");
collection.set('great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',"Residuo organico");
collection.set('tiger shark, Galeocerdo cuvieri',"No tengo información de como reciclarlo");
collection.set('hammerhead, hammerhead shark',"No tengo información de como reciclarlo");
collection.set('electric ray, crampfish, numbfish, torpedo',"No tengo información de como reciclarlo");
collection.set('stingray',"No tengo información de como reciclarlo");
collection.set('cock',"No tengo información de como reciclarlo");
collection.set('hen',"No tengo información de como reciclarlo");
collection.set('ostrich, Struthio camelus',"No tengo información de como reciclarlo");
collection.set('brambling, Fringilla montifringilla',"No tengo información de como reciclarlo");
collection.set('goldfinch, Carduelis carduelis',"No tengo información de como reciclarlo");
collection.set('house finch, linnet, Carpodacus mexicanus',"No tengo información de como reciclarlo");
collection.set('junco, snowbird',"No tengo información de como reciclarlo");
collection.set('indigo bunting, indigo finch, indigo bird, Passerina cyanea',"No tengo información de como reciclarlo");
collection.set('robin, American robin, Turdus migratorius',"No tengo información de como reciclarlo");
collection.set('bulbul',"No tengo información de como reciclarlo");
collection.set('jay',"No tengo información de como reciclarlo");
collection.set('magpie',"No tengo información de como reciclarlo");
collection.set('chickadee',"No tengo información de como reciclarlo");
collection.set('water ouzel, dipper',"No tengo información de como reciclarlo");
collection.set('kite',"Depositar tu papel o cartón en los contenedores habilitados para este producto\.Posteriormente este producto se envía a reciclar en un proceso que resulta mucho menos contaminante que la producción de papel desde cero\.");
collection.set('bald eagle, American eagle, Haliaeetus leucocephalus',"No tengo información de como reciclarlo");
collection.set('vulture',"No tengo información de como reciclarlo");
collection.set('great grey owl, great gray owl, Strix nebulosa',"No tengo información de como reciclarlo");
collection.set('European fire salamander, Salamandra salamandra',"No tengo información de como reciclarlo");
collection.set('common newt, Triturus vulgaris',"No tengo información de como reciclarlo");
collection.set('eft',"No tengo información de como reciclarlo");
collection.set('spotted salamander, Ambystoma maculatum',"No tengo información de como reciclarlo");
collection.set('axolotl, mud puppy, Ambystoma mexicanum',"No tengo información de como reciclarlo");
collection.set('bullfrog, Rana catesbeiana',"No tengo información de como reciclarlo");
collection.set('tree frog, tree-frog',"No tengo información de como reciclarlo");
collection.set('tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui',"No tengo información de como reciclarlo");
collection.set('loggerhead, loggerhead turtle, Caretta caretta',"No tengo información de como reciclarlo");
collection.set('leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea',"No tengo información de como reciclarlo");
collection.set('mud turtle',"No tengo información de como reciclarlo");
collection.set('terrapin',"No tengo información de como reciclarlo");
collection.set('box turtle, box tortoise',"No tengo información de como reciclarlo");
collection.set('banded gecko',"No tengo información de como reciclarlo");
collection.set('common iguana, iguana, Iguana iguana',"No tengo información de como reciclarlo");
collection.set('American chameleon, anole, Anolis carolinensis',"No tengo información de como reciclarlo");
collection.set('whiptail, whiptail lizard',"No tengo información de como reciclarlo");
collection.set('agama',"No tengo información de como reciclarlo");
collection.set('frilled lizard, Chlamydosaurus kingi',"No tengo información de como reciclarlo");
collection.set('alligator lizard',"No tengo información de como reciclarlo");
collection.set('Gila monster, Heloderma suspectum',"No tengo información de como reciclarlo");
collection.set('green lizard, Lacerta viridis',"No tengo información de como reciclarlo");
collection.set('African chameleon, Chamaeleo chamaeleon',"No tengo información de como reciclarlo");
collection.set('Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis',"No tengo información de como reciclarlo");
collection.set('African crocodile, Nile crocodile, Crocodylus niloticus',"No tengo información de como reciclarlo");
collection.set('American alligator, Alligator mississipiensis',"No tengo información de como reciclarlo");
collection.set('triceratops',"No tengo información de como reciclarlo");
collection.set('thunder snake, worm snake, Carphophis amoenus',"No tengo información de como reciclarlo");
collection.set('ringneck snake, ring-necked snake, ring snake',"No tengo información de como reciclarlo");
collection.set('hognose snake, puff adder, sand viper',"No tengo información de como reciclarlo");
collection.set('green snake, grass snake',"No tengo información de como reciclarlo");
collection.set('king snake, kingsnake',"No tengo información de como reciclarlo");
collection.set('garter snake, grass snake',"No tengo información de como reciclarlo");
collection.set('water snake',"No tengo información de como reciclarlo");
collection.set('vine snake',"No tengo información de como reciclarlo");
collection.set('night snake, Hypsiglena torquata',"No tengo información de como reciclarlo");
collection.set('boa constrictor, Constrictor constrictor',"No tengo información de como reciclarlo");
collection.set('rock python, rock snake, Python sebae',"No tengo información de como reciclarlo");
collection.set('Indian cobra, Naja naja',"No tengo información de como reciclarlo");
collection.set('green mamba',"No tengo información de como reciclarlo");
collection.set('sea snake',"No tengo información de como reciclarlo");
collection.set('horned viper, cerastes, sand viper, horned asp, Cerastes cornutus',"No tengo información de como reciclarlo");
collection.set('diamondback, diamondback rattlesnake, Crotalus adamanteus',"No tengo información de como reciclarlo");
collection.set('sidewinder, horned rattlesnake, Crotalus cerastes',"No tengo información de como reciclarlo");
collection.set('trilobite',"No tengo información de como reciclarlo");
collection.set('harvestman, daddy longlegs, Phalangium opilio',"No tengo información de como reciclarlo");
collection.set('scorpion',"No tengo información de como reciclarlo");
collection.set('black and gold garden spider, Argiope aurantia',"No tengo información de como reciclarlo");
collection.set('barn spider, Araneus cavaticus',"No tengo información de como reciclarlo");
collection.set('garden spider, Aranea diademata',"No tengo información de como reciclarlo");
collection.set('black widow, Latrodectus mactans',"No tengo información de como reciclarlo");
collection.set('tarantula',"No tengo información de como reciclarlo");
collection.set('wolf spider, hunting spider',"No tengo información de como reciclarlo");
collection.set('tick',"No tengo información de como reciclarlo");
collection.set('centipede',"No tengo información de como reciclarlo");
collection.set('black grouse',"No tengo información de como reciclarlo");
collection.set('ptarmigan',"No tengo información de como reciclarlo");
collection.set('ruffed grouse, partridge, Bonasa umbellus',"No tengo información de como reciclarlo");
collection.set('prairie chicken, prairie grouse, prairie fowl',"No tengo información de como reciclarlo");
collection.set('peacock',"No tengo información de como reciclarlo");
collection.set('quail',"No tengo información de como reciclarlo");
collection.set('partridge',"No tengo información de como reciclarlo");
collection.set('African grey, African gray, Psittacus erithacus',"No tengo información de como reciclarlo");
collection.set('macaw',"No tengo información de como reciclarlo");
collection.set('sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita',"No tengo información de como reciclarlo");
collection.set('lorikeet',"No tengo información de como reciclarlo");
collection.set('coucal',"No tengo información de como reciclarlo");
collection.set('bee eater',"No tengo información de como reciclarlo");
collection.set('hornbill',"No tengo información de como reciclarlo");
collection.set('hummingbird',"No tengo información de como reciclarlo");
collection.set('jacamar',"No tengo información de como reciclarlo");
collection.set('toucan',"No tengo información de como reciclarlo");
collection.set('drake',"No tengo información de como reciclarlo");
collection.set('red-breasted merganser, Mergus serrator',"No tengo información de como reciclarlo");
collection.set('goose',"No tengo información de como reciclarlo");
collection.set( 'black swan, Cygnus atratus',"No tengo información de como reciclarlo");
collection.set( 'tusker',"No tengo información de como reciclarlo");
collection.set( 'echidna, spiny anteater, anteater',"No tengo información de como reciclarlo");
collection.set( 'platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus',"No tengo información de como reciclarlo");
collection.set( 'wallaby, brush kangaroo',"No tengo información de como reciclarlo");
collection.set( 'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus',"No tengo información de como reciclarlo");
collection.set( 'wombat',"No tengo información de como reciclarlo");
collection.set( 'jelly fish',"No tengo información de como reciclarlo");
collection.set( 'sea anemone, anemone',"No tengo información de como reciclarlo");
collection.set( 'brain coral',"No tengo información de como reciclarlo");
collection.set( 'flatworm, platyhelminth',"No tengo información de como reciclarlo");
collection.set( 'nematode, nematode worm, roundworm',"No tengo información de como reciclarlo");
collection.set( 'conch',"No tengo información de como reciclarlo");
collection.set( 'snail',"No tengo información de como reciclarlo");
collection.set( 'slug',"No tengo información de como reciclarlo");
collection.set( 'sea slug, nudibranch',"No tengo información de como reciclarlo");
collection.set( 'chiton, coat-of-mail shell, sea cradle, polyplacophore',"No tengo información de como reciclarlo");
collection.set( 'chambered nautilus, pearly nautilus, nautilus',"No tengo información de como reciclarlo");
collection.set( 'Dungeness crab, Cancer magister',"No tengo información de como reciclarlo");
collection.set( 'rock crab, Cancer irroratus',"No tengo información de como reciclarlo");
collection.set( 'fiddler crab',"No tengo información de como reciclarlo");
collection.set( 'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica',"No tengo información de como reciclarlo");
collection.set( 'American lobster, Northern lobster, Maine lobster, Homarus americanus',"No tengo información de como reciclarlo");
collection.set( 'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish',"No tengo información de como reciclarlo");
collection.set( 'crayfish, crawfish, crawdad, crawdaddy',"No tengo información de como reciclarlo");
collection.set( 'hermit crab',"No tengo información de como reciclarlo");
collection.set( 'isopod',"No tengo información de como reciclarlo");
collection.set( 'white stork, Ciconia ciconia',"No tengo información de como reciclarlo");
collection.set( 'black stork, Ciconia nigra',"No tengo información de como reciclarlo");
collection.set( 'spoonbill',"No tengo información de como reciclarlo");
collection.set( 'flamingo',"No tengo información de como reciclarlo");
collection.set( 'little blue heron, Egretta caerulea',"No tengo información de como reciclarlo");
collection.set( 'American egret, great white heron, Egretta albus',"No tengo información de como reciclarlo");
collection.set( 'bittern',"No tengo información de como reciclarlo");
collection.set( 'crane',"No tengo información de como reciclarlo");
collection.set( 'limpkin, Aramus pictus',"No tengo información de como reciclarlo");
collection.set( 'European gallinule, Porphyrio porphyrio',"No tengo información de como reciclarlo");
collection.set( 'American coot, marsh hen, mud hen, water hen, Fulica americana',"No tengo información de como reciclarlo");
collection.set( 'bustard',"No tengo información de como reciclarlo");
collection.set( 'ruddy turnstone, Arenaria interpres',"No tengo información de como reciclarlo");
collection.set( 'red-backed sandpiper, dunlin, Erolia alpina',"No tengo información de como reciclarlo");
collection.set( 'redshank, Tringa totanus',"No tengo información de como reciclarlo");
collection.set( 'dowitcher',"No tengo información de como reciclarlo");
collection.set( 'oystercatcher, oyster catcher',"No tengo información de como reciclarlo");
collection.set( 'pelican',"No tengo información de como reciclarlo");
collection.set( 'king penguin, Aptenodytes patagonica',"No tengo información de como reciclarlo");
collection.set( 'albatross, mollymawk',"No tengo información de como reciclarlo");
collection.set( 'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus',"No tengo información de como reciclarlo");
collection.set( 'killer whale, killer, orca, grampus, sea wolf, Orcinus orca',"No tengo información de como reciclarlo");
collection.set( 'dugong, Dugong dugon',"No tengo información de como reciclarlo");
collection.set( 'sea lion',"No tengo información de como reciclarlo");
collection.set( 'Chihuahua',"No tengo información de como reciclarlo");
collection.set( 'Japanese spaniel',"No tengo información de como reciclarlo");
collection.set( 'Maltese dog, Maltese terrier, Maltese',"No tengo información de como reciclarlo");
collection.set( 'Pekinese, Pekingese, Peke',"No tengo información de como reciclarlo");
collection.set( 'Shih-Tzu',"No tengo información de como reciclarlo");
collection.set( 'Blenheim spaniel',"No tengo información de como reciclarlo");
collection.set( 'papillon',"No tengo información de como reciclarlo");
collection.set( 'toy terrier',"No tengo información de como reciclarlo");
collection.set( 'Rhodesian ridgeback',"No tengo información de como reciclarlo");
collection.set( 'Afghan hound, Afghan',"No tengo información de como reciclarlo");
collection.set( 'basset, basset hound',"No tengo información de como reciclarlo");
collection.set( 'beagle',"No tengo información de como reciclarlo");
collection.set( 'bloodhound, sleuthhound',"No tengo información de como reciclarlo");
collection.set( 'bluetick',"No tengo información de como reciclarlo");
collection.set( 'black-and-tan coonhound',"No tengo información de como reciclarlo");
collection.set( 'Walker hound, Walker foxhound',"No tengo información de como reciclarlo");
collection.set( 'English foxhound',"No tengo información de como reciclarlo");
collection.set( 'redbone',"No tengo información de como reciclarlo");
collection.set( 'borzoi, Russian wolfhound',"No tengo información de como reciclarlo");
collection.set( 'Irish wolfhound',"No tengo información de como reciclarlo");
collection.set( 'Italian greyhound',"No tengo información de como reciclarlo");
collection.set( 'whippet',"No tengo información de como reciclarlo");
collection.set( 'Ibizan hound, Ibizan Podenco',"No tengo información de como reciclarlo");
collection.set( 'Norwegian elkhound, elkhound',"No tengo información de como reciclarlo");
collection.set( 'otterhound, otter hound',"No tengo información de como reciclarlo");
collection.set( 'Saluki, gazelle hound',"No tengo información de como reciclarlo");
collection.set( 'Scottish deerhound, deerhound',"No tengo información de como reciclarlo");
collection.set( 'Weimaraner',"No tengo información de como reciclarlo");
collection.set( 'Staffordshire bullterrier, Staffordshire bull terrier',"No tengo información de como reciclarlo");
collection.set( 'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier',"No tengo información de como reciclarlo");
collection.set( 'Bedlington terrier',"No tengo información de como reciclarlo");
collection.set( 'Border terrier',"No tengo información de como reciclarlo");
collection.set( 'Kerry blue terrier',"No tengo información de como reciclarlo");
collection.set( 'Irish terrier',"No tengo información de como reciclarlo");
collection.set( 'Norfolk terrier',"No tengo información de como reciclarlo");
collection.set( 'Norwich terrier',"No tengo información de como reciclarlo");
collection.set( 'Yorkshire terrier',"No tengo información de como reciclarlo");
collection.set( 'wire-haired fox terrier',"No tengo información de como reciclarlo");
collection.set( 'Lakeland terrier',"No tengo información de como reciclarlo");
collection.set( 'Sealyham terrier, Sealyham',"No tengo información de como reciclarlo");
collection.set( 'Airedale, Airedale terrier',"No tengo información de como reciclarlo");
collection.set( 'cairn, cairn terrier',"No tengo información de como reciclarlo");
collection.set( 'Australian terrier',"No tengo información de como reciclarlo");
collection.set( 'Dandie Dinmont, Dandie Dinmont terrier',"No tengo información de como reciclarlo");
collection.set( 'Boston bull, Boston terrier',"No tengo información de como reciclarlo");
collection.set( 'miniature schnauzer',"No tengo información de como reciclarlo");
collection.set( 'giant schnauzer',"No tengo información de como reciclarlo");
collection.set( 'standard schnauzer',"No tengo información de como reciclarlo");
collection.set( 'Scotch terrier, Scottish terrier, Scottie',"No tengo información de como reciclarlo");
collection.set( 'Tibetan terrier, chrysanthemum dog',"No tengo información de como reciclarlo");
collection.set( 'silky terrier, Sydney silky',"No tengo información de como reciclarlo");
collection.set( 'soft-coated wheaten terrier',"No tengo información de como reciclarlo");
collection.set( 'West Highland white terrier',"No tengo información de como reciclarlo");
collection.set( 'Lhasa, Lhasa apso',"No tengo información de como reciclarlo");
collection.set( 'flat-coated retriever',"No tengo información de como reciclarlo");
collection.set( 'curly-coated retriever',"No tengo información de como reciclarlo");
collection.set( 'golden retriever',"No tengo información de como reciclarlo");
collection.set( 'Labrador retriever',"No tengo información de como reciclarlo");
collection.set( 'Chesapeake Bay retriever',"No tengo información de como reciclarlo");
collection.set( 'German short-haired pointer',"No tengo información de como reciclarlo");
collection.set( 'vizsla, Hungarian pointer',"No tengo información de como reciclarlo");
collection.set( 'English setter',"No tengo información de como reciclarlo");
collection.set( 'Irish setter, red setter',"No tengo información de como reciclarlo");
collection.set( 'Gordon setter',"No tengo información de como reciclarlo");
collection.set( 'Brittany spaniel',"No tengo información de como reciclarlo");
collection.set( 'clumber, clumber spaniel',"No tengo información de como reciclarlo");
collection.set( 'English springer, English springer spaniel',"No tengo información de como reciclarlo");
collection.set( 'Welsh springer spaniel',"No tengo información de como reciclarlo");
collection.set( 'cocker spaniel, English cocker spaniel, cocker',"No tengo información de como reciclarlo");
collection.set( 'Sussex spaniel',"No tengo información de como reciclarlo");
collection.set( 'Irish water spaniel',"No tengo información de como reciclarlo");
collection.set( 'kuvasz',"No tengo información de como reciclarlo");
collection.set( 'schipperke',"No tengo información de como reciclarlo");
collection.set( 'groenendael',"No tengo información de como reciclarlo");
collection.set( 'malinois',"No tengo información de como reciclarlo");
collection.set( 'briard',"No tengo información de como reciclarlo");
collection.set( 'kelpie',"No tengo información de como reciclarlo");
collection.set( 'komondor',"No tengo información de como reciclarlo");
collection.set( 'Old English sheepdog, bobtail',"No tengo información de como reciclarlo");
collection.set( 'Shetland sheepdog, Shetland sheep dog, Shetland',"No tengo información de como reciclarlo");
collection.set( 'collie',"No tengo información de como reciclarlo");
collection.set( 'Border collie',"No tengo información de como reciclarlo");
collection.set( 'Bouvier des Flandres, Bouviers des Flandres',"No tengo información de como reciclarlo");
collection.set( 'Rottweiler',"No tengo información de como reciclarlo");
collection.set( 'German shepherd, German shepherd dog, German police dog, alsatian',"No tengo información de como reciclarlo");
collection.set( 'Doberman, Doberman pinscher',"No tengo información de como reciclarlo");
collection.set( 'miniature pinscher',"No tengo información de como reciclarlo");
collection.set( 'Greater Swiss Mountain dog',"No tengo información de como reciclarlo");
collection.set( 'Bernese mountain dog',"No tengo información de como reciclarlo");
collection.set( 'Appenzeller',"No tengo información de como reciclarlo");
collection.set( 'EntleBucher',"No tengo información de como reciclarlo");
collection.set( 'boxer',"No tengo información de como reciclarlo");
collection.set( 'bull mastiff',"No tengo información de como reciclarlo");
collection.set( 'Tibetan mastiff',"No tengo información de como reciclarlo");
collection.set( 'French bulldog',"No tengo información de como reciclarlo");
collection.set( 'Great Dane',"No tengo información de como reciclarlo");
collection.set( 'Saint Bernard, St Bernard',"No tengo información de como reciclarlo");
collection.set( 'Eskimo dog, husky',"No tengo información de como reciclarlo");
collection.set( 'malamute, malemute, Alaskan malamute',"No tengo información de como reciclarlo");
collection.set( 'Siberian husky',"No tengo información de como reciclarlo");
collection.set( 'dalmatian, coach dog, carriage dog',"No tengo información de como reciclarlo");
collection.set( 'affenpinscher, monkey pinscher, monkey dog',"No tengo información de como reciclarlo");
collection.set( 'basenji',"No tengo información de como reciclarlo");
collection.set( 'pug, pug-dog',"No tengo información de como reciclarlo");
collection.set( 'Leonberg',"No tengo información de como reciclarlo");
collection.set( 'Newfoundland, Newfoundland dog',"No tengo información de como reciclarlo");
collection.set( 'Great Pyrenees',"No tengo información de como reciclarlo");
collection.set( 'Samoyed, Samoyede',"No tengo información de como reciclarlo");
collection.set( 'Pomeranian',"No tengo información de como reciclarlo");
collection.set( 'chow, chow chow',"No tengo información de como reciclarlo");
collection.set( 'keeshond',"No tengo información de como reciclarlo");
collection.set( 'Brabancon griffon',"No tengo información de como reciclarlo");
collection.set( 'Pembroke, Pembroke Welsh corgi',"No tengo información de como reciclarlo");
collection.set( 'Cardigan, Cardigan Welsh corgi',"No tengo información de como reciclarlo");
collection.set( 'toy poodle',"No tengo información de como reciclarlo");
collection.set( 'miniature poodle',"No tengo información de como reciclarlo");
collection.set( 'standard poodle',"No tengo información de como reciclarlo");
collection.set( 'Mexican hairless',"No tengo información de como reciclarlo");
collection.set( 'timber wolf, grey wolf, gray wolf, Canis lupus',"No tengo información de como reciclarlo");
collection.set( 'white wolf, Arctic wolf, Canis lupus tundrarum',"No tengo información de como reciclarlo");
collection.set( 'red wolf, maned wolf, Canis rufus, Canis niger',"No tengo información de como reciclarlo");
collection.set( 'coyote, prairie wolf, brush wolf, Canis latrans',"No tengo información de como reciclarlo");
collection.set( 'dingo, warrigal, warragal, Canis dingo',"No tengo información de como reciclarlo");
collection.set( 'dhole, Cuon alpinus',"No tengo información de como reciclarlo");
collection.set( 'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus',"No tengo información de como reciclarlo");
collection.set( 'hyena, hyaena',"No tengo información de como reciclarlo");
collection.set( 'red fox, Vulpes vulpes',"No tengo información de como reciclarlo");
collection.set( 'kit fox, Vulpes macrotis',"No tengo información de como reciclarlo");
collection.set( 'Arctic fox, white fox, Alopex lagopus',"No tengo información de como reciclarlo");
collection.set( 'grey fox, gray fox, Urocyon cinereoargenteus',"No tengo información de como reciclarlo");
collection.set( 'tabby, tabby cat',"No tengo información de como reciclarlo");
collection.set( 'tiger cat',"No tengo información de como reciclarlo");
collection.set( 'Persian cat',"No tengo información de como reciclarlo");
collection.set( 'Siamese cat, Siamese',"No tengo información de como reciclarlo");
collection.set( 'Egyptian cat',"No tengo información de como reciclarlo");
collection.set( 'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor',"No tengo información de como reciclarlo");
collection.set( 'lynx, catamount',"No tengo información de como reciclarlo");
collection.set( 'leopard, Panthera pardus',"No tengo información de como reciclarlo");
collection.set( 'snow leopard, ounce, Panthera uncia',"No tengo información de como reciclarlo");
collection.set( 'jaguar, panther, Panthera onca, Felis onca',"No tengo información de como reciclarlo");
collection.set( 'lion, king of beasts, Panthera leo',"No tengo información de como reciclarlo");
collection.set( 'tiger, Panthera tigris',"No tengo información de como reciclarlo");
collection.set( 'cheetah, chetah, Acinonyx jubatus',"No tengo información de como reciclarlo");
collection.set( 'brown bear, bruin, Ursus arctos',"No tengo información de como reciclarlo");
collection.set( 'American black bear, black bear, Ursus americanus, Euarctos americanus',"No tengo información de como reciclarlo");
collection.set( 'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus',"No tengo información de como reciclarlo");
collection.set( 'sloth bear, Melursus ursinus, Ursus ursinus',"No tengo información de como reciclarlo");
collection.set( 'mongoose',"No tengo información de como reciclarlo");
collection.set( 'meerkat, mierkat',"No tengo información de como reciclarlo");
collection.set( 'tiger beetle',"No tengo información de como reciclarlo");
collection.set( 'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle',"No tengo información de como reciclarlo");
collection.set( 'ground beetle, carabid beetle',"No tengo información de como reciclarlo");
collection.set( 'long-horned beetle, longicorn, longicorn beetle',"No tengo información de como reciclarlo");
collection.set( 'leaf beetle, chrysomelid',"No tengo información de como reciclarlo");
collection.set( 'dung beetle',"No tengo información de como reciclarlo");
collection.set( 'rhinoceros beetle',"No tengo información de como reciclarlo");
collection.set( 'weevil',"No tengo información de como reciclarlo");
collection.set( 'fly',"No tengo información de como reciclarlo");
collection.set( 'bee',"No tengo información de como reciclarlo");
collection.set( 'ant, emmet, pismire',"No tengo información de como reciclarlo");
collection.set( 'grasshopper, hopper',"No tengo información de como reciclarlo");
collection.set( 'cricket',"No tengo información de como reciclarlo");
collection.set( 'walking stick, walkingstick, stick insect',"No tengo información de como reciclarlo");
collection.set( 'cockroach, roach',"No tengo información de como reciclarlo");
collection.set( 'mantis, mantid',"No tengo información de como reciclarlo");
collection.set( 'cicada, cicala',"No tengo información de como reciclarlo");
collection.set( 'leafhopper',"No tengo información de como reciclarlo");
collection.set( 'lacewing, lacewing fly',"No tengo información de como reciclarlo");
collection.set( 'dragonfly, darning needle, devil\'s darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk',"No tengo información de como reciclarlo");
collection.set( 'damselfly',"No tengo información de como reciclarlo");
collection.set( 'admiral',"No tengo información de como reciclarlo");
collection.set( 'ringlet, ringlet butterfly',"No tengo información de como reciclarlo");
collection.set( 'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus',"No tengo información de como reciclarlo");
collection.set( 'cabbage butterfly',"No tengo información de como reciclarlo");
collection.set( 'sulphur butterfly, sulfur butterfly',"No tengo información de como reciclarlo");
collection.set( 'lycaenid, lycaenid butterfly',"No tengo información de como reciclarlo");
collection.set( 'starfish, sea star',"No tengo información de como reciclarlo");
collection.set( 'sea urchin',"No tengo información de como reciclarlo");
collection.set( 'sea cucumber, holothurian',"No tengo información de como reciclarlo");
collection.set( 'wood rabbit, cottontail, cottontail rabbit',"No tengo información de como reciclarlo");
collection.set( 'hare',"No tengo información de como reciclarlo");
collection.set( 'Angora, Angora rabbit',"No tengo información de como reciclarlo");
collection.set( 'hamster',"No tengo información de como reciclarlo");
collection.set( 'porcupine, hedgehog',"No tengo información de como reciclarlo");
collection.set( 'fox squirrel, eastern fox squirrel, Sciurus niger',"No tengo información de como reciclarlo");
collection.set( 'marmot',"No tengo información de como reciclarlo");
collection.set( 'beaver',"No tengo información de como reciclarlo");
collection.set( 'guinea pig, Cavia cobaya',"No tengo información de como reciclarlo");
collection.set( 'sorrel',"No tengo información de como reciclarlo");
collection.set( 'zebra',"No tengo información de como reciclarlo");
collection.set( 'hog, pig, grunter, squealer, Sus scrofa',"No tengo información de como reciclarlo");
collection.set( 'wild boar, boar, Sus scrofa',"No tengo información de como reciclarlo");
collection.set( 'warthog',"No tengo información de como reciclarlo");
collection.set( 'hippopotamus, hippo, river horse, Hippopotamus amphibius',"No tengo información de como reciclarlo");
collection.set( 'ox',"No tengo información de como reciclarlo");
collection.set( 'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis',"No tengo información de como reciclarlo");
collection.set( 'bison',"No tengo información de como reciclarlo");
collection.set( 'ram, tup',"No tengo información de como reciclarlo");
collection.set( 'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis',"No tengo información de como reciclarlo");
collection.set( 'ibex, Capra ibex',"No tengo información de como reciclarlo");
collection.set( 'hartebeest',"No tengo información de como reciclarlo");
collection.set( 'impala, Aepyceros melampus',"No tengo información de como reciclarlo");
collection.set( 'gazelle',"No tengo información de como reciclarlo");
collection.set( 'Arabian camel, dromedary, Camelus dromedarius',"No tengo información de como reciclarlo");
collection.set( 'llama',"No tengo información de como reciclarlo");
collection.set( 'weasel',"No tengo información de como reciclarlo");
collection.set( 'mink',"No tengo información de como reciclarlo");
collection.set( 'polecat, fitch, foulmart, foumart, Mustela putorius',"No tengo información de como reciclarlo");
collection.set( 'black-footed ferret, ferret, Mustela nigripes',"No tengo información de como reciclarlo");
collection.set( 'otter',"No tengo información de como reciclarlo");
collection.set( 'skunk, polecat, wood pussy',"No tengo información de como reciclarlo");
collection.set( 'badger',"No tengo información de como reciclarlo");
collection.set( 'armadillo',"No tengo información de como reciclarlo");
collection.set( 'three-toed sloth, ai, Bradypus tridactylus',"No tengo información de como reciclarlo");
collection.set( 'orangutan, orang, orangutang, Pongo pygmaeus',"No tengo información de como reciclarlo");
collection.set( 'gorilla, Gorilla gorilla',"No tengo información de como reciclarlo");
collection.set( 'chimpanzee, chimp, Pan troglodytes',"No tengo información de como reciclarlo");
collection.set( 'gibbon, Hylobates lar',"No tengo información de como reciclarlo");
collection.set( 'siamang, Hylobates syndactylus, Symphalangus syndactylus',"No tengo información de como reciclarlo");
collection.set( 'guenon, guenon monkey',"No tengo información de como reciclarlo");
collection.set( 'patas, hussar monkey, Erythrocebus patas',"No tengo información de como reciclarlo");
collection.set( 'baboon',"No tengo información de como reciclarlo");
collection.set( 'macaque',"No tengo información de como reciclarlo");
collection.set( 'langur',"No tengo información de como reciclarlo");
collection.set( 'colobus, colobus monkey',"No tengo información de como reciclarlo");
collection.set( 'proboscis monkey, Nasalis larvatus',"No tengo información de como reciclarlo");
collection.set( 'marmoset',"No tengo información de como reciclarlo");
collection.set( 'capuchin, ringtail, Cebus capucinus',"No tengo información de como reciclarlo");
collection.set( 'howler monkey, howler',"No tengo información de como reciclarlo");
collection.set( 'titi, titi monkey',"No tengo información de como reciclarlo");
collection.set( 'spider monkey, Ateles geoffroyi',"No tengo información de como reciclarlo");
collection.set( 'squirrel monkey, Saimiri sciureus',"No tengo información de como reciclarlo");
collection.set( 'Madagascar cat, ring-tailed lemur, Lemur catta',"No tengo información de como reciclarlo");
collection.set( 'indri, indris, Indri indri, Indri brevicaudatus',"No tengo información de como reciclarlo");
collection.set( 'Indian elephant, Elephas maximus',"No tengo información de como reciclarlo");
collection.set( 'African elephant, Loxodonta africana',"No tengo información de como reciclarlo");
collection.set( 'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens',"No tengo información de como reciclarlo");
collection.set( 'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca',"No tengo información de como reciclarlo");
collection.set( 'barracouta, snoek',"No tengo información de como reciclarlo");
collection.set( 'eel',"No tengo información de como reciclarlo");
collection.set( 'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch',"No tengo información de como reciclarlo");
collection.set( 'rock beauty, Holocanthus tricolor',"No tengo información de como reciclarlo");
collection.set( 'anemone fish',"No tengo información de como reciclarlo");
collection.set( 'sturgeon',"No tengo información de como reciclarlo");
collection.set( 'gar, garfish, garpike, billfish, Lepisosteus osseus',"No tengo información de como reciclarlo");
collection.set( 'lionfish',"No tengo información de como reciclarlo");
collection.set( 'puffer, pufferfish, blowfish, globefish',"No tengo información de como reciclarlo");
collection.set( 'abacus',"No tengo información de como reciclarlo");
collection.set( 'abaya',"No tengo información de como reciclarlo");
collection.set( 'academic gown, academic robe, judge\'s robe',"No tengo información de como reciclarlo");
collection.set( 'accordion, piano accordion, squeeze box',"No tengo información de como reciclarlo");
collection.set( 'acoustic guitar',"No tengo información de como reciclarlo");
collection.set( 'aircraft carrier, carrier, flattop, attack aircraft carrier',"No tengo información de como reciclarlo");
collection.set( 'airliner',"No tengo información de como reciclarlo");
collection.set( 'airship, dirigible',"No tengo información de como reciclarlo");
collection.set( 'altar',"No tengo información de como reciclarlo");
collection.set( 'ambulance',"No tengo información de como reciclarlo");
collection.set( 'amphibian, amphibious vehicle',"No tengo información de como reciclarlo");
collection.set( 'analog clock',"No tengo información de como reciclarlo");
collection.set( 'apiary, bee house',"No tengo información de como reciclarlo");
collection.set( 'apron',"No tengo información de como reciclarlo");
collection.set( 'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin',"No tengo información de como reciclarlo");
collection.set( 'assault rifle, assault gun',"No tengo información de como reciclarlo");
collection.set( 'backpack, back pack, knapsack, packsack, rucksack, haversack',"No tengo información de como reciclarlo");
collection.set( 'bakery, bakeshop, bakehouse',"No tengo información de como reciclarlo");
collection.set( 'balance beam, beam',"No tengo información de como reciclarlo");
collection.set( 'balloon',"No tengo información de como reciclarlo");
collection.set( 'ballpoint, ballpoint pen, ballpen, Biro',"No tengo información de como reciclarlo");
collection.set( 'Band Aid',"No tengo información de como reciclarlo");
collection.set( 'banjo',"No tengo información de como reciclarlo");
collection.set( 'bannister, banister, balustrade, balusters, handrail',"No tengo información de como reciclarlo");
collection.set( 'barbell',"No tengo información de como reciclarlo");
collection.set( 'barber chair',"No tengo información de como reciclarlo");
collection.set( 'barbershop',"No tengo información de como reciclarlo");
collection.set( 'barn',"No tengo información de como reciclarlo");
collection.set( 'barometer',"No tengo información de como reciclarlo");
collection.set( 'barrel, cask',"No tengo información de como reciclarlo");
collection.set( 'barrow, garden cart, lawn cart, wheelbarrow',"No tengo información de como reciclarlo");
collection.set( 'baseball',"No tengo información de como reciclarlo");
collection.set( 'basketball',"No tengo información de como reciclarlo");
collection.set( 'bassinet',"No tengo información de como reciclarlo");
collection.set( 'bassoon',"No tengo información de como reciclarlo");
collection.set( 'bathing cap, swimming cap',"No tengo información de como reciclarlo");
collection.set( 'bath towel',"No tengo información de como reciclarlo");
collection.set( 'bathtub, bathing tub, bath, tub',"No tengo información de como reciclarlo");
collection.set( 'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon',"No tengo información de como reciclarlo");
collection.set( 'beacon, lighthouse, beacon light, pharos',"No tengo información de como reciclarlo");
collection.set( 'beaker',"No tengo información de como reciclarlo");
collection.set( 'bearskin, busby, shako',"No tengo información de como reciclarlo");
collection.set( 'beer bottle',"Vidrio");
collection.set( 'beer glass',"No tengo información de como reciclarlo");
collection.set( 'bell cote, bell cot',"No tengo información de como reciclarlo");
collection.set( 'bib',"No tengo información de como reciclarlo");
collection.set( 'bicycle-built-for-two, tandem bicycle, tandem',"No tengo información de como reciclarlo");
collection.set( 'bikini, two-piece',"No tengo información de como reciclarlo");
collection.set( 'binder, ring-binder',"No tengo información de como reciclarlo");
collection.set( 'binoculars, field glasses, opera glasses',"No tengo información de como reciclarlo");
collection.set( 'birdhouse',"No tengo información de como reciclarlo");
collection.set( 'boathouse',"No tengo información de como reciclarlo");
collection.set( 'bobsled, bobsleigh, bob',"No tengo información de como reciclarlo");
collection.set( 'bolo tie, bolo, bola tie, bola',"No tengo información de como reciclarlo");
collection.set( 'bonnet, poke bonnet',"No tengo información de como reciclarlo");
collection.set( 'bookcase',"No tengo información de como reciclarlo");
collection.set( 'bookshop, bookstore, bookstall',"No tengo información de como reciclarlo");
collection.set( 'bottlecap',"Dirígete al primer contenedor correspondiente y tira el envase\. Será recogido y trasladado a una planta para su previo tratamiento y recuperación\.");
collection.set( 'bow',"No tengo información de como reciclarlo");
collection.set( 'bow tie, bow-tie, bowtie',"No tengo información de como reciclarlo");
collection.set( 'brass, memorial tablet, plaque',"No tengo información de como reciclarlo");
collection.set( 'brassiere, bra, bandeau',"No tengo información de como reciclarlo");
collection.set( 'breakwater, groin, groyne, mole, bulwark, seawall, jetty',"No tengo información de como reciclarlo");
collection.set( 'breastplate, aegis, egis',"No tengo información de como reciclarlo");
collection.set( 'broom',"No tengo información de como reciclarlo");
collection.set( 'bucket, pail',"No tengo información de como reciclarlo");
collection.set( 'buckle',"No tengo información de como reciclarlo");
collection.set( 'bulletproof vest',"No tengo información de como reciclarlo");
collection.set( 'bullet train, bullet',"No tengo información de como reciclarlo");
collection.set( 'butcher shop, meat market',"No tengo información de como reciclarlo");
collection.set( 'cab, hack, taxi, taxicab',"No tengo información de como reciclarlo");
collection.set( 'caldron, cauldron',"No tengo información de como reciclarlo");
collection.set( 'candle, taper, wax light',"No tengo información de como reciclarlo");
collection.set( 'cannon',"No tengo información de como reciclarlo");
collection.set( 'canoe',"No tengo información de como reciclarlo");
collection.set( 'can opener, tin opener',"No tengo información de como reciclarlo");
collection.set( 'cardigan',"No tengo información de como reciclarlo");
collection.set( 'car mirror',"No tengo información de como reciclarlo");
collection.set( 'carousel, carrousel, merry-go-round, roundabout, whirligig',"No tengo información de como reciclarlo");
collection.set( 'carpenter\'s kit, tool kit',"No tengo información de como reciclarlo");
collection.set( 'carton',"No tengo información de como reciclarlo");
collection.set( 'car wheel',"No tengo información de como reciclarlo");
collection.set( 'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM',"No tengo información de como reciclarlo");
collection.set( 'cassette',"No tengo información de como reciclarlo");
collection.set( 'cassette player',"No tengo información de como reciclarlo");
collection.set( 'castle',"No tengo información de como reciclarlo");
collection.set( 'catamaran',"No tengo información de como reciclarlo");
collection.set( 'CD player',"No tengo información de como reciclarlo");
collection.set( 'cello, violoncello',"No tengo información de como reciclarlo");
collection.set( 'cellular telephone, cellular phone, cellphone, cell, mobile phone',"No tengo información de como reciclarlo");
collection.set( 'chain',"No tengo información de como reciclarlo");
collection.set( 'chainlink fence',"No tengo información de como reciclarlo");
collection.set( 'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour',"No tengo información de como reciclarlo");
collection.set( 'chain saw, chainsaw',"No tengo información de como reciclarlo");
collection.set( 'chest',"No tengo información de como reciclarlo");
collection.set( 'chiffonier, commode',"No tengo información de como reciclarlo");
collection.set( 'chime, bell, gong',"No tengo información de como reciclarlo");
collection.set( 'china cabinet, china closet',"No tengo información de como reciclarlo");
collection.set( 'Christmas stocking',"No tengo información de como reciclarlo");
collection.set( 'church, church building',"No tengo información de como reciclarlo");
collection.set( 'cinema, movie theater, movie theatre, movie house, picture palace',"No tengo información de como reciclarlo");
collection.set( 'cleaver, meat cleaver, chopper',"No tengo información de como reciclarlo");
collection.set( 'cliff dwelling',"No tengo información de como reciclarlo");
collection.set( 'cloak',"No tengo información de como reciclarlo");
collection.set( 'clog, geta, patten, sabot',"No tengo información de como reciclarlo");
collection.set( 'cocktail shaker',"No tengo información de como reciclarlo");
collection.set( 'coffee mug',"No tengo información de como reciclarlo");
collection.set( 'coffeepot',"No tengo información de como reciclarlo");
collection.set( 'coil, spiral, volute, whorl, helix',"No tengo información de como reciclarlo");
collection.set( 'combination lock',"No tengo información de como reciclarlo");
collection.set( 'computer keyboard, keypad',"No tengo información de como reciclarlo");
collection.set( 'confectionery, confectionary, candy store',"No tengo información de como reciclarlo");
collection.set( 'container ship, containership, container vessel',"No tengo información de como reciclarlo");
collection.set( 'convertible',"No tengo información de como reciclarlo");
collection.set( 'corkscrew, bottle screw',"No tengo información de como reciclarlo");
collection.set( 'cornet, horn, trumpet, trump',"No tengo información de como reciclarlo");
collection.set( 'cowboy boot',"No tengo información de como reciclarlo");
collection.set( 'cowboy hat, ten-gallon hat',"No tengo información de como reciclarlo");
collection.set( 'cradle',"No tengo información de como reciclarlo");
collection.set( 'crane',"No tengo información de como reciclarlo");
collection.set( 'crash helmet',"No tengo información de como reciclarlo");
collection.set( 'crate',"No tengo información de como reciclarlo");
collection.set( 'crib, cot',"No tengo información de como reciclarlo");
collection.set( 'Crock Pot',"No tengo información de como reciclarlo");
collection.set( 'croquet ball',"No tengo información de como reciclarlo");
collection.set( 'crutch',"No tengo información de como reciclarlo");
collection.set( 'cuirass',"No tengo información de como reciclarlo");
collection.set( 'dam, dike, dyke',"No tengo información de como reciclarlo");
collection.set( 'desk',"No tengo información de como reciclarlo");
collection.set( 'desktop computer',"No tengo información de como reciclarlo");
collection.set( 'dial telephone, dial phone',"No tengo información de como reciclarlo");
collection.set( 'diaper, nappy, napkin',"No tengo información de como reciclarlo");
collection.set( 'digital clock',"No tengo información de como reciclarlo");
collection.set( 'digital watch',"No tengo información de como reciclarlo");
collection.set( 'dining table, board',"No tengo información de como reciclarlo");
collection.set( 'dishrag, dishcloth',"No tengo información de como reciclarlo");
collection.set( 'dishwasher, dish washer, dishwashing machine',"No tengo información de como reciclarlo");
collection.set( 'disk brake, disc brake',"No tengo información de como reciclarlo");
collection.set( 'dock, dockage, docking facility',"No tengo información de como reciclarlo");
collection.set( 'dogsled, dog sled, dog sleigh',"No tengo información de como reciclarlo");
collection.set( 'dome',"No tengo información de como reciclarlo");
collection.set( 'doormat, welcome mat',"No tengo información de como reciclarlo");
collection.set( 'drilling platform, offshore rig',"No tengo información de como reciclarlo");
collection.set( 'drum, membranophone, tympan',"No tengo información de como reciclarlo");
collection.set( 'drumstick',"No tengo información de como reciclarlo");
collection.set( 'dumbbell',"No tengo información de como reciclarlo");
collection.set( 'Dutch oven',"No tengo información de como reciclarlo");
collection.set( 'electric fan, blower',"No tengo información de como reciclarlo");
collection.set( 'electric guitar',"No tengo información de como reciclarlo");
collection.set( 'electric locomotive',"No tengo información de como reciclarlo");
collection.set( 'entertainment center',"No tengo información de como reciclarlo");
collection.set( 'envelope',"Depositar tu papel o cartón en los contenedores habilitados para este producto\. Posteriormente este producto se envía a reciclar en un proceso que resulta mucho menos contaminante que la producción de papel desde cero.");
collection.set( 'espresso maker',"No tengo información de como reciclarlo");
collection.set( 'face powder',"No tengo información de como reciclarlo");
collection.set( 'feather boa, boa',"No tengo información de como reciclarlo");
collection.set( 'file, file cabinet, filing cabinet',"No tengo información de como reciclarlo");
collection.set( 'fireboat',"No tengo información de como reciclarlo");
collection.set( 'fire engine, fire truck',"No tengo información de como reciclarlo");
collection.set( 'fire screen, fireguard',"No tengo información de como reciclarlo");
collection.set( 'flagpole, flagstaff',"No tengo información de como reciclarlo");
collection.set( 'flute, transverse flute',"No tengo información de como reciclarlo");
collection.set( 'folding chair',"No tengo información de como reciclarlo");
collection.set( 'football helmet',"No tengo información de como reciclarlo");
collection.set( 'forklift',"No tengo información de como reciclarlo");
collection.set( 'fountain',"No tengo información de como reciclarlo");
collection.set( 'fountain pen',"No tengo información de como reciclarlo");
collection.set( 'four-poster',"No tengo información de como reciclarlo");
collection.set( 'freight car',"No tengo información de como reciclarlo");
collection.set( 'French horn, horn',"No tengo información de como reciclarlo");
collection.set( 'frying pan, frypan, skillet',"No tengo información de como reciclarlo");
collection.set( 'fur coat',"No tengo información de como reciclarlo");
collection.set( 'garbage truck, dustcart',"No tengo información de como reciclarlo");
collection.set( 'gasmask, respirator, gas helmet',"No tengo información de como reciclarlo");
collection.set( 'gas pump, gasoline pump, petrol pump, island dispenser',"No tengo información de como reciclarlo");
collection.set( 'goblet',"No tengo información de como reciclarlo");
collection.set( 'go-kart',"No tengo información de como reciclarlo");
collection.set( 'golf ball',"No tengo información de como reciclarlo");
collection.set( 'golfcart, golf cart',"No tengo información de como reciclarlo");
collection.set( 'gondola',"No tengo información de como reciclarlo");
collection.set( 'gong, tam-tam',"No tengo información de como reciclarlo");
collection.set( 'gown',"No tengo información de como reciclarlo");
collection.set( 'grand piano, grand',"No tengo información de como reciclarlo");
collection.set( 'greenhouse, nursery, glasshouse',"No tengo información de como reciclarlo");
collection.set( 'grille, radiator grille',"No tengo información de como reciclarlo");
collection.set( 'grocery store, grocery, food market, market',"No tengo información de como reciclarlo");
collection.set( 'guillotine',"No tengo información de como reciclarlo");
collection.set( 'hair slide',"No tengo información de como reciclarlo");
collection.set( 'hair spray',"No tengo información de como reciclarlo");
collection.set( 'half track',"No tengo información de como reciclarlo");
collection.set( 'hammer',"No tengo información de como reciclarlo");
collection.set( 'hamper',"Dirígete al primer contenedor correspondiente y tira el envase\”.”Será recogido y trasladado a una planta para su previo tratamiento y recuperación\”.”");
collection.set( 'hand blower, blow dryer, blow drier, hair dryer, hair drier',"No tengo información de como reciclarlo");
collection.set( 'hand-held computer, hand-held microcomputer',"No tengo información de como reciclarlo");
collection.set( 'handkerchief, hankie, hanky, hankey',"No tengo información de como reciclarlo");
collection.set( 'hard disc, hard disk, fixed disk',"No tengo información de como reciclarlo");
collection.set( 'harmonica, mouth organ, harp, mouth harp',"No tengo información de como reciclarlo");
collection.set( 'harp',"No tengo información de como reciclarlo");
collection.set( 'harvester, reaper',"No tengo información de como reciclarlo");
collection.set( 'hatchet',"No tengo información de como reciclarlo");
collection.set( 'holster',"No tengo información de como reciclarlo");
collection.set( 'home theater, home theatre',"No tengo información de como reciclarlo");
collection.set( 'honeycomb',"No tengo información de como reciclarlo");
collection.set( 'hook, claw',"No tengo información de como reciclarlo");
collection.set( 'hoopskirt, crinoline',"No tengo información de como reciclarlo");
collection.set( 'horizontal bar, high bar',"No tengo información de como reciclarlo");
collection.set( 'horse cart, horse-cart',"No tengo información de como reciclarlo");
collection.set( 'hourglass',"No tengo información de como reciclarlo");
collection.set( 'iPod',"No tengo información de como reciclarlo");
collection.set( 'iron, smoothing iron',"No tengo información de como reciclarlo");
collection.set( 'jack-o\'-lantern',"No tengo información de como reciclarlo");
collection.set( 'jean, blue jean, denim',"No tengo información de como reciclarlo");
collection.set( 'jeep, landrover',"No tengo información de como reciclarlo");
collection.set( 'jersey, T-shirt, tee shirt',"No tengo información de como reciclarlo");
collection.set( 'jigsaw puzzle',"No tengo información de como reciclarlo");
collection.set( 'jinrikisha, ricksha, rickshaw',"No tengo información de como reciclarlo");
collection.set( 'joystick',"No tengo información de como reciclarlo");
collection.set( 'kimono',"No tengo información de como reciclarlo");
collection.set( 'knee pad',"No tengo información de como reciclarlo");
collection.set( 'knot',"No tengo información de como reciclarlo");
collection.set( 'lab coat, laboratory coat',"No tengo información de como reciclarlo");
collection.set( 'ladle',"No tengo información de como reciclarlo");
collection.set( 'lampshade, lamp shade',"No tengo información de como reciclarlo");
collection.set( 'laptop, laptop computer',"No tengo información de como reciclarlo");
collection.set( 'lawn mower, mower',"No tengo información de como reciclarlo");
collection.set( 'lens cap, lens cover',"No tengo información de como reciclarlo");
collection.set( 'letter opener, paper knife, paperknife',"No tengo información de como reciclarlo");
collection.set( 'library',"No tengo información de como reciclarlo");
collection.set( 'lifeboat',"No tengo información de como reciclarlo");
collection.set( 'lighter, light, igniter, ignitor',"No tengo información de como reciclarlo");
collection.set( 'limousine, limo',"No tengo información de como reciclarlo");
collection.set( 'liner, ocean liner',"No tengo información de como reciclarlo");
collection.set( 'lipstick, lip rouge',"No tengo información de como reciclarlo");
collection.set( 'Loafer',"No tengo información de como reciclarlo");
collection.set( 'lotion',"No tengo información de como reciclarlo");
collection.set( 'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system',"No tengo información de como reciclarlo");
collection.set( 'loupe, jeweler\'s loupe',"No tengo información de como reciclarlo");
collection.set( 'lumbermill, sawmill',"No tengo información de como reciclarlo");
collection.set( 'magnetic compass',"No tengo información de como reciclarlo");
collection.set( 'mailbag, postbag',"No tengo información de como reciclarlo");
collection.set( 'mailbox, letter box',"No tengo información de como reciclarlo");
collection.set( 'maillot',"No tengo información de como reciclarlo");
collection.set( 'maillot, tank suit',"No tengo información de como reciclarlo");
collection.set( 'manhole cover',"No tengo información de como reciclarlo");
collection.set( 'maraca',"No tengo información de como reciclarlo");
collection.set( 'marimba, xylophone',"No tengo información de como reciclarlo");
collection.set( 'mask',"No tengo información de como reciclarlo");
collection.set( 'matchstick',"No tengo información de como reciclarlo");
collection.set( 'maypole',"No tengo información de como reciclarlo");
collection.set( 'maze, labyrinth',"No tengo información de como reciclarlo");
collection.set( 'measuring cup',"No tengo información de como reciclarlo");
collection.set( 'medicine chest, medicine cabinet',"No tengo información de como reciclarlo");
collection.set( 'megalith, megalithic structure',"No tengo información de como reciclarlo");
collection.set( 'microphone, mike',"No tengo información de como reciclarlo");
collection.set( 'microwave, microwave oven',"No tengo información de como reciclarlo");
collection.set( 'military uniform',"No tengo información de como reciclarlo");
collection.set( 'milk can',"No tengo información de como reciclarlo");
collection.set( 'minibus',"No tengo información de como reciclarlo");
collection.set( 'miniskirt, mini',"No tengo información de como reciclarlo");
collection.set( 'minivan',"No tengo información de como reciclarlo");
collection.set( 'missile',"No tengo información de como reciclarlo");
collection.set( 'mitten',"No tengo información de como reciclarlo");
collection.set( 'mixing bowl',"No tengo información de como reciclarlo");
collection.set( 'mobile home, manufactured home',"No tengo información de como reciclarlo");
collection.set( 'Model T',"No tengo información de como reciclarlo");
collection.set( 'modem',"No tengo información de como reciclarlo");
collection.set( 'monastery',"No tengo información de como reciclarlo");
collection.set( 'monitor',"No tengo información de como reciclarlo");
collection.set( 'moped',"No tengo información de como reciclarlo");
collection.set( 'mortar',"No tengo información de como reciclarlo");
collection.set( 'mortarboard',"No tengo información de como reciclarlo");
collection.set( 'mosque',"No tengo información de como reciclarlo");
collection.set( 'mosquito net',"No tengo información de como reciclarlo");
collection.set( 'motor scooter, scooter',"No tengo información de como reciclarlo");
collection.set( 'mountain bike, all-terrain bike, off-roader',"No tengo información de como reciclarlo");
collection.set( 'mountain tent',"No tengo información de como reciclarlo");
collection.set( 'mouse, computer mouse',"No tengo información de como reciclarlo");
collection.set( 'mousetrap',"No tengo información de como reciclarlo");
collection.set( 'moving van',"No tengo información de como reciclarlo");
collection.set( 'muzzle',"No tengo información de como reciclarlo");
collection.set( 'nail',"No tengo información de como reciclarlo");
collection.set( 'neck brace',"No tengo información de como reciclarlo");
collection.set( 'necklace',"No tengo información de como reciclarlo");
collection.set( 'nipple',"No tengo información de como reciclarlo");
collection.set( 'notebook, notebook computer',"No tengo información de como reciclarlo");
collection.set( 'obelisk',"No tengo información de como reciclarlo");
collection.set( 'oboe, hautboy, hautbois',"No tengo información de como reciclarlo");
collection.set( 'ocarina, sweet potato',"No tengo información de como reciclarlo");
collection.set( 'odometer, hodometer, mileometer, milometer',"No tengo información de como reciclarlo");
collection.set( 'oil filter',"No tengo información de como reciclarlo");
collection.set( 'organ, pipe organ',"No tengo información de como reciclarlo");
collection.set( 'oscilloscope, scope, cathode-ray oscilloscope, CRO',"No tengo información de como reciclarlo");
collection.set( 'overskirt',"No tengo información de como reciclarlo");
collection.set( 'oxcart',"No tengo información de como reciclarlo");
collection.set( 'oxygen mask',"No tengo información de como reciclarlo");
collection.set( 'packet',"No tengo información de como reciclarlo");
collection.set( 'paddle, boat paddle',"No tengo información de como reciclarlo");
collection.set( 'paddlewheel, paddle wheel',"No tengo información de como reciclarlo");
collection.set( 'padlock',"No tengo información de como reciclarlo");
collection.set( 'paintbrush',"No tengo información de como reciclarlo");
collection.set( 'pajama, pyjama, pj\'s, jammies',"No tengo información de como reciclarlo");
collection.set( 'palace',"No tengo información de como reciclarlo");
collection.set( 'panpipe, pandean pipe, syrinx',"No tengo información de como reciclarlo");
collection.set( 'paper towel',"Depositar tu papel o cartón en los contenedores habilitados para este producto\.Posteriormente este producto se envía a reciclar en un proceso que resulta mucho menos contaminante que la producción de papel desde cero\.");
collection.set( 'parachute, chute',"No tengo información de como reciclarlo");
collection.set( 'parallel bars, bars',"No tengo información de como reciclarlo");
collection.set( 'park bench',"No tengo información de como reciclarlo");
collection.set( 'parking meter',"No tengo información de como reciclarlo");
collection.set( 'passenger car, coach, carriage',"No tengo información de como reciclarlo");
collection.set( 'patio, terrace',"No tengo información de como reciclarlo");
collection.set( 'pay-phone, pay-station',"No tengo información de como reciclarlo");
collection.set( 'pedestal, plinth, footstall',"No tengo información de como reciclarlo");
collection.set( 'pencil box, pencil case',"No tengo información de como reciclarlo");
collection.set( 'pencil sharpener',"No tengo información de como reciclarlo");
collection.set( 'perfume, essence',"No tengo información de como reciclarlo");
collection.set( 'Petri dish',"No tengo información de como reciclarlo");
collection.set( 'photocopier',"No tengo información de como reciclarlo");
collection.set('tench, Tinca tinca',"No tengo información de como reciclarlo");
collection.set( 'pick, plectrum, plectron',"No tengo información de como reciclarlo");
collection.set( 'pickelhaube',"No tengo información de como reciclarlo");
collection.set( 'picket fence, paling',"No tengo información de como reciclarlo");
collection.set( 'pickup, pickup truck',"No tengo información de como reciclarlo");
collection.set( 'pier',"No tengo información de como reciclarlo");
collection.set( 'piggy bank, penny bank',"No tengo información de como reciclarlo");
collection.set( 'pill bottle',"Dirígete al primer contenedor correspondiente y tira el envase\. Será recogido y trasladado a una planta para su previo tratamiento y recuperación\.");
collection.set( 'pillow',"No tengo información de como reciclarlo");
collection.set( 'ping-pong ball',"No tengo información de como reciclarlo");
collection.set( 'pinwheel',"Depositar tu papel o cartón en los contenedores habilitados para este producto\.Posteriormente este producto se envía a reciclar en un proceso que resulta mucho menos contaminante que la producción de papel desde cero\.");
collection.set( 'pirate, pirate ship',"No tengo información de como reciclarlo");
collection.set( 'pitcher, ewer',"No tengo información de como reciclarlo");
collection.set( 'plane, carpenter\'s plane, woodworking plane',"No tengo información de como reciclarlo");
collection.set( 'planetarium',"No tengo información de como reciclarlo");
collection.set( 'plastic bag',"No tengo información de como reciclarlo");
collection.set( 'plate rack',"No tengo información de como reciclarlo");
collection.set( 'plow, plough',"No tengo información de como reciclarlo");
collection.set( 'plunger, plumber\'s helper',"No tengo información de como reciclarlo");
collection.set( 'Polaroid camera, Polaroid Land camera',"No tengo información de como reciclarlo");
collection.set( 'pole',"No tengo información de como reciclarlo");
collection.set( 'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria',"No tengo información de como reciclarlo");
collection.set( 'poncho',"No tengo información de como reciclarlo");
collection.set( 'pool table, billiard table, snooker table',"No tengo información de como reciclarlo");
collection.set( 'pop bottle, soda bottle',"Dirígete al primer contenedor correspondiente y tira el envase\. Será recogido y trasladado a una planta para su previo tratamiento y recuperación\.");
collection.set( 'pot, flowerpot',"No tengo información de como reciclarlo");
collection.set( 'potter\'s wheel',"No tengo información de como reciclarlo");
collection.set( 'power drill',"No tengo información de como reciclarlo");
collection.set( 'prayer rug, prayer mat',"No tengo información de como reciclarlo");
collection.set( 'printer',"No tengo información de como reciclarlo");
collection.set( 'prison, prison house',"No tengo información de como reciclarlo");
collection.set( 'projectile, missile',"No tengo información de como reciclarlo");
collection.set( 'projector',"No tengo información de como reciclarlo");
collection.set( 'puck, hockey puck',"No tengo información de como reciclarlo");
collection.set( 'punching bag, punch bag, punching ball, punchball',"Depositar tu papel o cartón en los contenedores habilitados para este producto\.Posteriormente este producto se envía a reciclar en un proceso que resulta mucho menos contaminante que la producción de papel desde cero\.");
collection.set( 'purse',"No tengo información de como reciclarlo");
collection.set( 'quill, quill pen',"No tengo información de como reciclarlo");
collection.set( 'quilt, comforter, comfort, puff',"No tengo información de como reciclarlo");
collection.set( 'racer, race car, racing car',"No tengo información de como reciclarlo");
collection.set( 'racket, racquet',"No tengo información de como reciclarlo");
collection.set( 'radiator',"No tengo información de como reciclarlo");
collection.set( 'radio, wireless',"Para este tipo de productos, es importante llevarselo a mano de obra calificada, preparada para desechar los múltiples tipos de productos toxicos en un electronico.");
collection.set( 'radio telescope, radio reflector',"No tengo información de como reciclarlo");
collection.set( 'rain barrel',"No tengo información de como reciclarlo");
collection.set( 'recreational vehicle, RV, R.V.',"No tengo información de como reciclarlo");
collection.set( 'reel',"No tengo información de como reciclarlo");
collection.set( 'reflex camera',"No tengo información de como reciclarlo");
collection.set( 'refrigerator, icebox',"No tengo información de como reciclarlo");
collection.set( 'remote control, remote',"No tengo información de como reciclarlo");
collection.set( 'restaurant, eating house, eating place, eatery',"No tengo información de como reciclarlo");
collection.set( 'revolver, six-gun, six-shooter',"No tengo información de como reciclarlo");
collection.set( 'rifle',"No tengo información de como reciclarlo");
collection.set( 'rocking chair, rocker',"No tengo información de como reciclarlo");
collection.set( 'rotisserie',"No tengo información de como reciclarlo");
collection.set( 'rubber eraser, rubber, pencil eraser',"No tengo información de como reciclarlo");
collection.set( 'rugby ball',"No tengo información de como reciclarlo");
collection.set( 'rule, ruler',"No tengo información de como reciclarlo");
collection.set( 'running shoe',"No tengo información de como reciclarlo");
collection.set( 'safe',"No tengo información de como reciclarlo");
collection.set( 'safety pin',"No tengo información de como reciclarlo");
collection.set( 'saltshaker, salt shaker',"No tengo información de como reciclarlo");
collection.set( 'sandal',"No tengo información de como reciclarlo");
collection.set( 'sarong',"No tengo información de como reciclarlo");
collection.set( 'sax, saxophone',"No tengo información de como reciclarlo");
collection.set( 'scabbard',"No tengo información de como reciclarlo");
collection.set( 'scale, weighing machine',"No tengo información de como reciclarlo");
collection.set( 'school bus',"No tengo información de como reciclarlo");
collection.set( 'schooner',"No tengo información de como reciclarlo");
collection.set( 'scoreboard',"No tengo información de como reciclarlo");
collection.set( 'screen, CRT screen',"No tengo información de como reciclarlo");
collection.set( 'screw',"No tengo información de como reciclarlo");
collection.set( 'screwdriver',"No tengo información de como reciclarlo");
collection.set( 'seat belt, seatbelt',"No tengo información de como reciclarlo");
collection.set( 'sewing machine',"No tengo información de como reciclarlo");
collection.set( 'shield, buckler',"No tengo información de como reciclarlo");
collection.set( 'shoe shop, shoe-shop, shoe store',"No tengo información de como reciclarlo");
collection.set( 'shoji',"No tengo información de como reciclarlo");
collection.set( 'shopping basket',"No tengo información de como reciclarlo");
collection.set( 'shopping cart',"No tengo información de como reciclarlo");
collection.set( 'shovel',"No tengo información de como reciclarlo");
collection.set( 'shower cap',"No tengo información de como reciclarlo");
collection.set( 'shower curtain',"No tengo información de como reciclarlo");
collection.set( 'ski',"No tengo información de como reciclarlo");
collection.set( 'ski mask',"No tengo información de como reciclarlo");
collection.set( 'sleeping bag',"No tengo información de como reciclarlo");
collection.set( 'slide rule, slipstick',"No tengo información de como reciclarlo");
collection.set( 'sliding door',"No tengo información de como reciclarlo");
collection.set( 'slot, one-armed bandit',"No tengo información de como reciclarlo");
collection.set( 'snorkel',"No tengo información de como reciclarlo");
collection.set( 'snowmobile',"No tengo información de como reciclarlo");
collection.set( 'snowplow, snowplough',"No tengo información de como reciclarlo");
collection.set( 'soap dispenser',"No tengo información de como reciclarlo");
collection.set( 'soccer ball',"No tengo información de como reciclarlo");
collection.set( 'sock',"No tengo información de como reciclarlo");
collection.set( 'solar dish, solar collector, solar furnace',"No tengo información de como reciclarlo");
collection.set( 'sombrero',"No tengo información de como reciclarlo");
collection.set( 'soup bowl',"No tengo información de como reciclarlo");
collection.set( 'space bar',"No tengo información de como reciclarlo");
collection.set( 'space heater',"No tengo información de como reciclarlo");
collection.set( 'space shuttle',"No tengo información de como reciclarlo");
collection.set( 'spatula',"No tengo información de como reciclarlo");
collection.set( 'speedboat',"No tengo información de como reciclarlo");
collection.set( 'spider web, spider\'s web',"No tengo información de como reciclarlo");
collection.set( 'spindle',"No tengo información de como reciclarlo");
collection.set( 'sports car, sport car',"No tengo información de como reciclarlo");
collection.set( 'spotlight, spot',"No tengo información de como reciclarlo");
collection.set( 'stage',"No tengo información de como reciclarlo");
collection.set( 'steam locomotive',"No tengo información de como reciclarlo");
collection.set( 'steel arch bridge',"No tengo información de como reciclarlo");
collection.set( 'steel drum',"No tengo información de como reciclarlo");
collection.set( 'stethoscope',"No tengo información de como reciclarlo");
collection.set( 'stole',"No tengo información de como reciclarlo");
collection.set( 'stone wall',"No tengo información de como reciclarlo");
collection.set( 'stopwatch, stop watch',"No tengo información de como reciclarlo");
collection.set( 'stove',"No tengo información de como reciclarlo");
collection.set( 'strainer',"No tengo información de como reciclarlo");
collection.set( 'streetcar, tram, tramcar, trolley, trolley car',"No tengo información de como reciclarlo");
collection.set( 'stretcher',"No tengo información de como reciclarlo");
collection.set( 'studio couch, day bed',"No tengo información de como reciclarlo");
collection.set( 'stupa, tope',"No tengo información de como reciclarlo");
collection.set( 'submarine, pigboat, sub, U-boat',"No tengo información de como reciclarlo");
collection.set( 'suit, suit of clothes',"No tengo información de como reciclarlo");
collection.set( 'sundial',"No tengo información de como reciclarlo");
collection.set( 'sunglass',"No tengo información de como reciclarlo");
collection.set( 'sunglasses, dark glasses, shades',"No tengo información de como reciclarlo");
collection.set( 'sunscreen, sunblock, sun blocker',"No tengo información de como reciclarlo");
collection.set( 'suspension bridge',"No tengo información de como reciclarlo");
collection.set( 'swab, swob, mop',"No tengo información de como reciclarlo");
collection.set( 'sweatshirt',"No tengo información de como reciclarlo");
collection.set( 'swimming trunks, bathing trunks',"No tengo información de como reciclarlo");
collection.set( 'swing',"No tengo información de como reciclarlo");
collection.set( 'switch, electric switch, electrical switch',"No tengo información de como reciclarlo");
collection.set( 'syringe',"No tengo información de como reciclarlo");
collection.set( 'table lamp',"No tengo información de como reciclarlo");
collection.set( 'tank, army tank, armored combat vehicle, armoured combat vehicle',"No tengo información de como reciclarlo");
collection.set( 'tape player',"No tengo información de como reciclarlo");
collection.set( 'teapot',"No tengo información de como reciclarlo");
collection.set( 'teddy, teddy bear',"No tengo información de como reciclarlo");
collection.set( 'television, television system',"No tengo información de como reciclarlo");
collection.set( 'tennis ball',"No tengo información de como reciclarlo");
collection.set( 'thatch, thatched roof',"No tengo información de como reciclarlo");
collection.set( 'theater curtain, theatre curtain',"No tengo información de como reciclarlo");
collection.set( 'thimble',"No tengo información de como reciclarlo");
collection.set( 'thresher, thrasher, threshing machine',"No tengo información de como reciclarlo");
collection.set( 'throne',"No tengo información de como reciclarlo");
collection.set( 'tile roof',"No tengo información de como reciclarlo");
collection.set( 'toaster',"No tengo información de como reciclarlo");
collection.set( 'tobacco shop, tobacconist shop, tobacconist',"No tengo información de como reciclarlo");
collection.set( 'toilet seat',"No tengo información de como reciclarlo");
collection.set( 'torch',"No tengo información de como reciclarlo");
collection.set( 'totem pole',"No tengo información de como reciclarlo");
collection.set( 'tow truck, tow car, wrecker',"No tengo información de como reciclarlo");
collection.set( 'toyshop',"No tengo información de como reciclarlo");
collection.set( 'tractor',"No tengo información de como reciclarlo");
collection.set( 'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi',"No tengo información de como reciclarlo");
collection.set( 'tray',"No tengo información de como reciclarlo");
collection.set( 'trench coat',"No tengo información de como reciclarlo");
collection.set( 'tricycle, trike, velocipede',"No tengo información de como reciclarlo");
collection.set( 'trimaran',"No tengo información de como reciclarlo");
collection.set( 'tripod',"No tengo información de como reciclarlo");
collection.set( 'triumphal arch',"No tengo información de como reciclarlo");
collection.set( 'trolleybus, trolley coach, trackless trolley',"No tengo información de como reciclarlo");
collection.set( 'trombone',"No tengo información de como reciclarlo");
collection.set( 'tub, vat',"No tengo información de como reciclarlo");
collection.set( 'turnstile',"No tengo información de como reciclarlo");
collection.set( 'typewriter keyboard',"No tengo información de como reciclarlo");
collection.set( 'umbrella',"No tengo información de como reciclarlo");
collection.set( 'unicycle, monocycle',"No tengo información de como reciclarlo");
collection.set( 'upright, upright piano',"No tengo información de como reciclarlo");
collection.set( 'vacuum, vacuum cleaner',"No tengo información de como reciclarlo");
collection.set( 'vase',"La unica forma de reciclarlo es ponerlo en los depositos de basura indicados, y en el caso que el vidrio este sano, se puede reutilizar de distintas formas.");
collection.set( 'vault',"No tengo información de como reciclarlo");
collection.set( 'velvet',"No tengo información de como reciclarlo");
collection.set( 'vending machine',"No tengo información de como reciclarlo");
collection.set( 'vestment',"No tengo información de como reciclarlo");
collection.set( 'viaduct',"No tengo información de como reciclarlo");
collection.set( 'violin, fiddle',"No tengo información de como reciclarlo");
collection.set( 'volleyball',"No tengo información de como reciclarlo");
collection.set( 'waffle iron',"No tengo información de como reciclarlo");
collection.set( 'wall clock',"No tengo información de como reciclarlo");
collection.set( 'wallet, billfold, notecase, pocketbook',"No tengo información de como reciclarlo");
collection.set( 'wardrobe, closet, press',"No tengo información de como reciclarlo");
collection.set( 'warplane, military plane',"No tengo información de como reciclarlo");
collection.set( 'washbasin, handbasin, washbowl, lavabo, wash-hand basin',"No tengo información de como reciclarlo");
collection.set( 'washer, automatic washer, washing machine',"No tengo información de como reciclarlo");
collection.set( 'water bottle',"Dirígete al primer contenedor correspondiente y tira el envase\. Será recogido y trasladado a una planta para su previo tratamiento y recuperación\.");
collection.set( 'water jug',"No tengo información de como reciclarlo");
collection.set( 'water tower',"No tengo información de como reciclarlo");
collection.set( 'whiskey jug',"No tengo información de como reciclarlo");
collection.set( 'whistle',"No tengo información de como reciclarlo");
collection.set( 'wig',"No tengo información de como reciclarlo");
collection.set( 'window screen',"No tengo información de como reciclarlo");
collection.set( 'window shade',"No tengo información de como reciclarlo");
collection.set( 'Windsor tie',"No tengo información de como reciclarlo");
collection.set( 'wine bottle',"Vidrio");
collection.set( 'wing',"No tengo información de como reciclarlo");
collection.set( 'wok',"No tengo información de como reciclarlo");
collection.set( 'wooden spoon',"No tengo información de como reciclarlo");
collection.set( 'wool, woolen, woollen',"No tengo información de como reciclarlo");
collection.set( 'worm fence, snake fence, snake-rail fence, Virginia fence',"No tengo información de como reciclarlo");
collection.set( 'wreck',"No tengo información de como reciclarlo");
collection.set( 'yawl',"No tengo información de como reciclarlo");
collection.set( 'yurt',"No tengo información de como reciclarlo");
collection.set( 'web site, website, internet site, site',"No tengo información de como reciclarlo");
collection.set( 'comic book',"Depositar tu papel o cartón en los contenedores habilitados para este producto\.Posteriormente este producto se envía a reciclar en un proceso que resulta mucho menos contaminante que la producción de papel desde cero\.");
collection.set( 'crossword puzzle, crossword',"No tengo información de como reciclarlo");
collection.set( 'street sign',"No tengo información de como reciclarlo");
collection.set( 'traffic light, traffic signal, stoplight',"No tengo información de como reciclarlo");
collection.set( 'book jacket, dust cover, dust jacket, dust wrapper',"Depositar tu papel o cartón en los contenedores habilitados para este producto\.Posteriormente este producto se envía a reciclar en un proceso que resulta mucho menos contaminante que la producción de papel desde cero\.");
collection.set( 'menu',"No tengo información de como reciclarlo");
collection.set( 'plate',"No tengo información de como reciclarlo");
collection.set( 'guacamole',"No tengo información de como reciclarlo");
collection.set( 'consomme',"No tengo información de como reciclarlo");
collection.set( 'hot pot, hotpot',"No tengo información de como reciclarlo");
collection.set( 'trifle',"No tengo información de como reciclarlo");
collection.set( 'ice cream, icecream',"No tengo información de como reciclarlo");
collection.set( 'ice lolly, lolly, lollipop, popsicle',"No tengo información de como reciclarlo");
collection.set( 'French loaf',"No tengo información de como reciclarlo");
collection.set( 'bagel, beigel',"No tengo información de como reciclarlo");
collection.set( 'pretzel',"No tengo información de como reciclarlo");
collection.set( 'cheeseburger',"No tengo información de como reciclarlo");
collection.set( 'hotdog, hot dog, red hot',"No tengo información de como reciclarlo");
collection.set( 'mashed potato',"No tengo información de como reciclarlo");
collection.set( 'head cabbage',"No tengo información de como reciclarlo");
collection.set( 'broccoli',"No tengo información de como reciclarlo");
collection.set( 'cauliflower',"No tengo información de como reciclarlo");
collection.set( 'zucchini, courgette',"No tengo información de como reciclarlo");
collection.set( 'spaghetti squash',"No tengo información de como reciclarlo");
collection.set( 'acorn squash',"No tengo información de como reciclarlo");
collection.set( 'butternut squash',"No tengo información de como reciclarlo");
collection.set( 'cucumber, cuke',"No tengo información de como reciclarlo");
collection.set( 'artichoke, globe artichoke',"No tengo información de como reciclarlo");
collection.set( 'bell pepper',"No tengo información de como reciclarlo");
collection.set( 'cardoon',"No tengo información de como reciclarlo");
collection.set( 'mushroom',"No tengo información de como reciclarlo");
collection.set( 'Granny Smith',"No tengo información de como reciclarlo");
collection.set( 'strawberry',"No tengo información de como reciclarlo");
collection.set( 'orange',"No tengo información de como reciclarlo");
collection.set( 'lemon',"No tengo información de como reciclarlo");
collection.set( 'fig',"No tengo información de como reciclarlo");
collection.set( 'pineapple, ananas',"No tengo información de como reciclarlo");
collection.set( 'banana',"No tengo información de como reciclarlo");
collection.set( 'jackfruit, jak, jack',"No tengo información de como reciclarlo");
collection.set( 'custard apple',"No tengo información de como reciclarlo");
collection.set( 'pomegranate',"No tengo información de como reciclarlo");
collection.set( 'hay',"No tengo información de como reciclarlo");
collection.set( 'carbonara',"No tengo información de como reciclarlo");
collection.set( 'chocolate sauce, chocolate syrup',"No tengo información de como reciclarlo");
collection.set( 'dough',"No tengo información de como reciclarlo");
collection.set( 'meat loaf, meatloaf',"No tengo información de como reciclarlo");
collection.set( 'pizza, pizza pie',"No tengo información de como reciclarlo");
collection.set( 'potpie',"No tengo información de como reciclarlo");
collection.set( 'burrito',"No tengo información de como reciclarlo");
collection.set( 'red wine',"No tengo información de como reciclarlo");
collection.set( 'espresso',"No tengo información de como reciclarlo");
collection.set( 'cup',"No tengo información de como reciclarlo");
collection.set( 'eggnog',"No tengo información de como reciclarlo");
collection.set( 'alp',"No tengo información de como reciclarlo");
collection.set( 'bubble',"No tengo información de como reciclarlo");
collection.set( 'cliff, drop, drop-off',"No tengo información de como reciclarlo");
collection.set( 'coral reef',"No tengo información de como reciclarlo");
collection.set( 'geyser',"No tengo información de como reciclarlo");
collection.set( 'lakeside, lakeshore',"No tengo información de como reciclarlo");
collection.set( 'promontory, headland, head, foreland',"No tengo información de como reciclarlo");
collection.set( 'sandbar, sand bar',"No tengo información de como reciclarlo");
collection.set( 'seashore, coast, seacoast, sea-coast',"No tengo información de como reciclarlo");
collection.set( 'valley, vale',"No tengo información de como reciclarlo");
collection.set( 'volcano',"No tengo información de como reciclarlo");
collection.set( 'ballplayer, baseball player',"No tengo información de como reciclarlo");
collection.set( 'groom, bridegroom',"No tengo información de como reciclarlo");
collection.set( 'scuba diver',"No tengo información de como reciclarlo");
collection.set( 'rapeseed',"No tengo información de como reciclarlo");
collection.set( 'daisy',"No tengo información de como reciclarlo");
collection.set( 'yellow lady\'s slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum',"No tengo información de como reciclarlo");
collection.set( 'corn',"No tengo información de como reciclarlo");
collection.set( 'acorn',"No tengo información de como reciclarlo");
collection.set( 'hip, rose hip, rosehip',"No tengo información de como reciclarlo");
collection.set( 'buckeye, horse chestnut, conker',"No tengo información de como reciclarlo");
collection.set( 'coral fungus',"No tengo información de como reciclarlo");
collection.set( 'agaric',"No tengo información de como reciclarlo");
collection.set( 'gyromitra',"No tengo información de como reciclarlo");
collection.set( 'stinkhorn, carrion fungus',"No tengo información de como reciclarlo");
collection.set( 'earthstar',"No tengo información de como reciclarlo");
collection.set( 'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa',"No tengo información de como reciclarlo");
collection.set( 'bolete',"No tengo información de como reciclarlo");
collection.set( 'ear, spike, capitulum',"No tengo información de como reciclarlo");
collection.set( 'toilet tissue, toilet paper, bathroom tissue',"Depositar tu papel o cartón en los contenedores habilitados para este producto\.Posteriormente este producto se envía a reciclar en un proceso que resulta mucho menos contaminante que la producción de papel desde cero\."); 

const tips=collection.get(props)
return(tips)
}



export default hashmap


